### ISSUE TITLE
DC Offset Calibration of Various Blocks

### ISSUE THREAD

**Issue by RyanEGuerra** [myriadrf/LMS7002M-driver#10]
On startup, there are a series of self-calibration blocks for DC offset correction that should be run. Experience with the LMS6002D also shows that they should be re-run periodically as the equipment warms up for best performance. There also was a specific order in which the calibrations had to be run, since later blocks in the chain depended on performance of earlier blocks.

The desired API should run the entire DC offset calibration sequence on command.

**Comment by guruofquality** [comment]
Currently, the set_bandwidth() calls into the lime provided baseband and frontend calibration routines. Additional corrections can be handled digitally in the TSP sections. We have API hooks for these as well.
