### ISSUE TITLE
TDD Mode PLL Sharing

### ISSUE THREAD

**Issue by RyanEGuerra** [myriadrf/LMS7002M-driver#11]
The LMS7002M appears to handle TDD mode a lot more sanely than the LMS6002D did. It now allows you to run the Tx and Rx mixers off a single PLL to improve power consumption (significant) and avoid re-locking or powering down extra PLLs when switching modes.

I'd like to be able to configure this ability in TDD mode. Perhaps a more general API that selects TDD and FDD mode (I think Fairwaves wants FDD mode) and then how you use your PLLs would be in order.

Running off a single PLL also has implications for transmit/receive beamforming, so that's pretty important here.

**Comment by guruofquality** [comment]
Added as LMS7002M_sxt_to_sxr()
