### ISSUE TITLE
tuning of RX and TX LO synthesizers

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LMS7002M-driver#2]
Given some new information about the VCO ranges and tuning algorithm, we should be able to fill this in.

**[VCOH] count: 2,**
**6.306 GHz,**
**7.714 GHz,**

**[VCOL] count: 2,**
**3.8 GHz,**
**5.222 GHz,**

**Comment by RyanEGuerra** [comment]
Agreed. This is critical for everything.

**Comment by guruofquality** [comment]
The values calculated by the algorithm match the GUI tool: https://github.com/myriadrf/LMS7002M-driver/commit/a363dab6d7b5de698d6e082794df49032e6936be

I will close this after confirmed testing. But the VCO selection algorithm is showing signs of life.

**Comment by RyanEGuerra** [comment]
We've tested this and it appears to be working. I'm going to close it so everyone gets a sense of satisfaction.
