### ISSUE TITLE
api control for analog gain adjustment

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LMS7002M-driver#3]

**Comment by RyanEGuerra** [comment]
Also agree with this. The API should boundary-check input gain values. Make sure to distinguish between code words for gains and actually set gain values (-11 dB vs code 0x4e9, say) in the API. Ideally, we just select log-linear gain values and the complexity happens behind the scenes.

One thing I will mention here is that I'll be testing different ways of implementing AGC in real-time. One way might be to have the baseband monitor RSSI values from the LMS (I'm still not sure how that's supposed to work) and calculate/set gain values directly via SPI.

The reason why I mention that here is that setting Rx gains is probably timing critical.

**Comment by guruofquality** [comment]
So far we have RX calls for RBB PGA, and RFE TIA and LNA. All calls bounds check and take gain in dB.

```
/*!
* Set the PGA gain for the RX baseband.
* \param self an instance of the LMS7002M driver
* \param channel the channel LMS_CHA or LMS_CHB
* \param gain the gain value in dB -12.0 to 19.0
* \return the actual gain value in dB
*/
LMS7002M_API double LMS7002M_rbb_set_pga(LMS7002M_t *self, const LMS7002M_chan_t channel, const double gain);

/*!
* Set the LNA gain for the RX RF frontend.
* \param self an instance of the LMS7002M driver
* \param channel the channel LMS_CHA or LMS_CHB
* \param gain the gain value in dB 0 to 30
* \return the actual gain value in dB
*/
LMS7002M_API double LMS7002M_rfe_set_lna(LMS7002M_t *self, const LMS7002M_chan_t channel, const double gain);

/*!
* Set the TIAL gain for the RX RF frontend.
* \param self an instance of the LMS7002M driver
* \param channel the channel LMS_CHA or LMS_CHB
* \param gain the gain value in dB 0 to 12
* \return the actual gain value in dB
*/
LMS7002M_API double LMS7002M_rfe_set_tia(LMS7002M_t *self, const LMS7002M_chan_t channel, const double gain);
```
