### ISSUE TITLE
baseband loopback calls

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LMS7002M-driver#4]
tx bb -> rx bb

**Comment by RyanEGuerra** [comment]
I also agree with this API for testing baseband connectivity.

**Comment by guruofquality** [comment]
TX baseband loopback configured through LMS7002M_tbb_enable_loopback() using LMS7002M_TBB_LB_\* defines. RX baseband loopback configured through LMS7002M_rbb_set_path() using LMS7002M_RBB_LB_\* defines.

The soapy sdr wrapper has hooks for setting baseband loopback mode through the writeSetting key/value pair API call. 

```

     *
     * - TBB_ENABLE_LOOPBACK(path) - enable TX baseband loopback.
     *   Use LB_DISCONNECTED, LB_DAC_CURRENT, LB_LB_LADDER, or LB_MAIN_TBB for the path.
     *
     * - RBB_SET_PATH(path) set the RX baseband input path.
     *   Use BYP, LBF, HBF for bypassing or filter path.
     *   Use LB_BYP, LB_LBF, LB_HBF for loopback versions.
```
