### ISSUE TITLE
RF loopback calls

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LMS7002M-driver#5]
tx rf -> rx rf

**Comment by RyanEGuerra** [comment]
I concur with this ticket. RF loopback will most likely be a necessary self-calibration mode.

**Comment by guruofquality** [comment]
This is supported through LMS7002M_rfe_set_path() using LMS7002M_RFE_LB1 and LMS7002M_RFE_LB2. In addition, LMS7002M_trf_enable_loopback() is automatically set accordingly.

Using the soapy sdr wrapper, this hook was also exposed through the set antenna API. Setting LB1/LB2 enables the rf loopback mode.
