### ISSUE TITLE
Tuning and Setting LPF Bandwidths

### ISSUE THREAD

**Issue by RyanEGuerra** [myriadrf/LMS7002M-driver#7]
There is an LPF bandwidth tuning calibration that should occur on each power-up of the chip to tune the corner frequency.

We found that on the LMD6002D, most of the later calibration steps were quite sensitive to this calibration and poor corner calibration in general led to some nasty signal integrity issues. 

This is separate from the LOFT calibration sequence.

So the desired APIs are a calibration routine for LPF corner frequency, and a separate API for selecting the LPF filter cutoff. It appears that there are high and low LPF paths, so the selection API should automagically route to the correct block.

**Comment by guruofquality** [comment]
The LMS7002M_tbb_set_filter_bw() and LMS7002M_rbb_set_filter_bw() calls select the filter baseband path based on frequency and uses the lime provided self-calibration routines.
